# Generated by Django 2.1.7 on 2020-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
