# Generated by Django 3.2.3 on 2021-10-15 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fuel_supplier_payment.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel_supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=fuel_supplier_payment.models.increment_Activity_id, max_length=20, null=True)),
                ('SOA_Date_received', models.CharField(blank=True, max_length=100)),
                ('Fuel_provider', models.CharField(blank=True, choices=[('SHELL', 'SHELL'), ('Petron Corporation', 'Petron Corporation'), ('Pilipinas Shell Petroleum Corp.', 'Pilipinas Shell Petroleum Corp.')], max_length=50, null=True)),
                ('SOA_billdate', models.CharField(blank=True, max_length=100)),
                ('SOA_current_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('SOA_outstanding_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('Payee', models.CharField(blank=True, choices=[('Globe', 'Globe'), ('Innove', 'Innove'), ('Byan', 'Bayan')], max_length=10, null=True)),
                ('SOA_attached', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_initiated', models.DateField(auto_now=True)),
                ('Date_forwarded', models.CharField(blank=True, max_length=100)),
                ('F_SLA', models.CharField(blank=True, max_length=10, null=True)),
                ('Deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFuel_supplier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Activity_id', models.CharField(default=fuel_supplier_payment.models.increment_Activity_id, max_length=20, null=True)),
                ('SOA_Date_received', models.CharField(blank=True, max_length=100)),
                ('Fuel_provider', models.CharField(blank=True, choices=[('SHELL', 'SHELL'), ('Petron Corporation', 'Petron Corporation'), ('Pilipinas Shell Petroleum Corp.', 'Pilipinas Shell Petroleum Corp.')], max_length=50, null=True)),
                ('SOA_billdate', models.CharField(blank=True, max_length=100)),
                ('SOA_current_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('SOA_outstanding_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('Payee', models.CharField(blank=True, choices=[('Globe', 'Globe'), ('Innove', 'Innove'), ('Byan', 'Bayan')], max_length=10, null=True)),
                ('SOA_attached', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_initiated', models.DateField(blank=True, editable=False)),
                ('Date_forwarded', models.CharField(blank=True, max_length=100)),
                ('F_SLA', models.CharField(blank=True, max_length=10, null=True)),
                ('Deadline', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fuel_supplier',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
