# Generated by Django 3.2.3 on 2021-10-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_supplier_payment', '0002_auto_20211015_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_supplier',
            name='Date_forwarded',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_supplier',
            name='Date_initiated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_supplier',
            name='Fuel_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_supplier',
            name='SOA_Date_received',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_supplier',
            name='SOA_billdate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfuel_supplier',
            name='Date_forwarded',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfuel_supplier',
            name='Date_initiated',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfuel_supplier',
            name='Fuel_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfuel_supplier',
            name='SOA_Date_received',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfuel_supplier',
            name='SOA_billdate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
