# Generated by Django 3.2.3 on 2022-03-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_supplier_payment', '0005_auto_20220316_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_supplier',
            name='liters',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalfuel_supplier',
            name='liters',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
