# Generated by Django 3.2.3 on 2022-03-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_supplier_payment', '0006_auto_20220317_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel_supplier',
            name='Deadline',
        ),
        migrations.RemoveField(
            model_name='fuel_supplier',
            name='F_SLA',
        ),
        migrations.RemoveField(
            model_name='historicalfuel_supplier',
            name='Deadline',
        ),
        migrations.RemoveField(
            model_name='historicalfuel_supplier',
            name='F_SLA',
        ),
    ]
