# Generated by Django 3.2.3 on 2022-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_supplier_payment', '0010_auto_20220318_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel_supplier_dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(max_length=20, null=True)),
                ('SOA_Date_received', models.CharField(blank=True, max_length=100, null=True)),
                ('Fuel_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('Cost_Center', models.CharField(blank=True, max_length=100, null=True)),
                ('SOA_billdate', models.DateField(blank=True, null=True)),
                ('SOA_current_amount', models.FloatField(blank=True, max_length=50, null=True)),
                ('SOA_outstanding_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('Payee', models.CharField(blank=True, max_length=10, null=True)),
                ('SOA_attached', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_initiated', models.DateField(auto_now=True, null=True)),
                ('Date_forwarded', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('liters', models.FloatField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
