# Generated by Django 2.1.7 on 2020-12-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs_log',
            name='Action_taken',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
