# Generated by Django 2.1.7 on 2020-12-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs_log',
            name='Date_received',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
