# Generated by Django 2.1.7 on 2020-12-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLog', '0002_auto_20201211_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs_log',
            name='Date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
