# Generated by Django 2.1.7 on 2021-01-05 17:41

import CustomerLog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLog', '0003_auto_20210105_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs_log',
            name='Date_resolved_inital',
            field=CustomerLog.models.MytypeField(blank=True, null=True),
        ),
    ]
