# Generated by Django 2.1.7 on 2021-01-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLog', '0004_auto_20210105_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs_log',
            name='Date_resolved_inital',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
