# Generated by Django 2.1.7 on 2021-01-07 13:04

import CustomerLog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLog', '0006_auto_20210107_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs_log',
            name='Date_resolved_inital',
            field=CustomerLog.models.MytypeField(),
        ),
    ]
