# Generated by Django 2.1.7 on 2021-02-20 21:06

from django.db import migrations, models
import fleet_card.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fleet_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=fleet_card.models.increment_Activity_id, max_length=100)),
                ('STATUS', models.CharField(blank=True, max_length=100, null=True)),
                ('RECEIVED_REQUEST', models.CharField(blank=True, max_length=100, null=True)),
                ('DATE_VERIFIED', models.DateTimeField(blank=True, null=True)),
                ('DATE_RECEIVED', models.DateTimeField(blank=True, null=True)),
                ('DATE_ISSUED', models.DateTimeField(blank=True, null=True)),
                ('WORK_DAYS', models.CharField(blank=True, max_length=100, null=True)),
                ('CARD_NUMBER', models.CharField(blank=True, max_length=254, null=True)),
                ('NAME', models.CharField(blank=True, max_length=254)),
                ('COST_CENTER', models.CharField(blank=True, max_length=254, null=True)),
                ('PLATE_NUMBER', models.CharField(blank=True, max_length=254, null=True)),
                ('CARD_TYPE', models.CharField(blank=True, choices=[('VEHICLE CARD', 'VEHICLE CARD'), ('DUAL CARD', 'DUAL CARD'), ('SINGLE CARD', 'SINGLE CARD'), ('DRIVERS CARD', 'DRIVERS CARD')], max_length=100, null=True)),
                ('CABONILLA', models.CharField(blank=True, max_length=100, null=True)),
                ('STATION', models.CharField(blank=True, choices=[('PETRON', 'PETRON'), ('SHELL', 'SHELL'), ('METRO OIL', 'METRO OIL'), ('UNIOIL', 'UNIOIL'), ('PHOENIX', 'PHOENIX'), ('PTT', 'PTT'), ('CLEAN FUEL', 'CLEAN FUEL'), ('CALTEX', 'CALTEX'), ('SEA OIL', 'SEA OIL')], max_length=254, null=True)),
            ],
        ),
    ]
