# Generated by Django 3.2.3 on 2021-09-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet_card',
            name='CRF_NUMBER',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fleet_card',
            name='DATE_OF_CRF_RECEIVED',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fleet_card',
            name='REMARKS',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
