# Generated by Django 2.1.7 on 2021-02-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet_card',
            name='DATE_ISSUED',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fleet_card',
            name='DATE_RECEIVED',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fleet_card',
            name='DATE_VERIFIED',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fleet_card',
            name='NAME',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
