# Generated by Django 3.2.3 on 2021-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_card', '0002_auto_20210929_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet_card',
            name='STATUS',
            field=models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
