# Generated by Django 2.1.7 on 2021-03-18 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMasterlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100, null=True)),
                ('Employee_Id', models.CharField(max_length=100, null=True)),
                ('Last_name', models.CharField(max_length=50, null=True)),
                ('First_name', models.CharField(max_length=50, null=True)),
                ('Middle_name', models.CharField(max_length=20, null=True)),
                ('Suffix', models.CharField(max_length=20, null=True)),
                ('Band', models.CharField(max_length=50, null=True)),
                ('Cost_center', models.CharField(max_length=100, null=True)),
                ('DIV_code', models.CharField(max_length=100, null=True)),
                ('Group', models.CharField(max_length=100, null=True)),
                ('Division', models.CharField(max_length=100, null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('Section', models.CharField(max_length=100, null=True)),
                ('Unit', models.CharField(max_length=100, null=True)),
                ('Sub_unit', models.CharField(max_length=100, null=True)),
                ('IS_ID', models.CharField(max_length=100, null=True)),
                ('IS_lastname', models.CharField(max_length=100, null=True)),
                ('IS_firstname', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('Area2', models.CharField(max_length=100, null=True)),
                ('Band_level', models.CharField(max_length=200, null=True)),
                ('Business_Title', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Benefit', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeMasterlist',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Company', models.CharField(max_length=100, null=True)),
                ('Employee_Id', models.CharField(max_length=100, null=True)),
                ('Last_name', models.CharField(max_length=50, null=True)),
                ('First_name', models.CharField(max_length=50, null=True)),
                ('Middle_name', models.CharField(max_length=20, null=True)),
                ('Suffix', models.CharField(max_length=20, null=True)),
                ('Band', models.CharField(max_length=50, null=True)),
                ('Cost_center', models.CharField(max_length=100, null=True)),
                ('DIV_code', models.CharField(max_length=100, null=True)),
                ('Group', models.CharField(max_length=100, null=True)),
                ('Division', models.CharField(max_length=100, null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('Section', models.CharField(max_length=100, null=True)),
                ('Unit', models.CharField(max_length=100, null=True)),
                ('Sub_unit', models.CharField(max_length=100, null=True)),
                ('IS_ID', models.CharField(max_length=100, null=True)),
                ('IS_lastname', models.CharField(max_length=100, null=True)),
                ('IS_firstname', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('Area2', models.CharField(max_length=100, null=True)),
                ('Band_level', models.CharField(max_length=200, null=True)),
                ('Business_Title', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Benefit', models.CharField(max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee masterlist',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
