# Generated by Django 2.1.7 on 2021-03-11 13:31

from django.db import migrations, models
import masterlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='vehilcle_status',
            field=models.CharField(blank=True, choices=[('Solved', 'Solved'), ('Transferred', 'Transferred'), ('Active', 'Active')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='vehilcle_status',
            field=models.CharField(blank=True, choices=[('Solved', 'Solved'), ('Transferred', 'Transferred'), ('Active', 'Active')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='Activity_Id',
            field=models.CharField(default=masterlist.models.increment_Activity_Id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Activity_Id',
            field=models.CharField(default=masterlist.models.increment_Activity_Id, max_length=100, null=True),
        ),
    ]
