# Generated by Django 2.1.7 on 2020-05-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='Status',
            field=models.CharField(blank=True, choices=[('Emailed', 'Emailed'), ('Not Emailed', 'Not Emailed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='Status',
            field=models.CharField(blank=True, choices=[('Emailed', 'Emailed'), ('Not Emailed', 'Not Emailed')], max_length=20, null=True),
        ),
    ]
