# Generated by Django 2.1.7 on 2021-02-23 15:47

from django.db import migrations, models
import masterlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvehiclemasterlist',
            old_name='IS_FIRST_NAME',
            new_name='IS_NAME',
        ),
        migrations.RenameField(
            model_name='vehiclemasterlist',
            old_name='IS_FIRST_NAME',
            new_name='IS_NAME',
        ),
        migrations.RemoveField(
            model_name='historicalvehiclemasterlist',
            name='IS_LAST_NAME',
        ),
        migrations.RemoveField(
            model_name='vehiclemasterlist',
            name='IS_LAST_NAME',
        ),
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='AREA',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='CHECKLIST_BY',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='AREA',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='CHECKLIST_BY',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='Activity_Id',
            field=models.CharField(default=masterlist.models.increment_Activity_Id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='BRAND',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Mitsubishi', 'Mitsubishi'), ('Ford', 'Ford'), ('Masda', 'Masda'), ('Isuzu', 'Isuzu'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('SuZuki', 'Suzuki'), ('Chevrolet', 'Chevrolet'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Bently', 'Bently'), ('Cadillac', 'Cadillac'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('GMC', 'GMC'), ('Genesis', 'Genesis'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mini', 'Mini'), ('Porsche', 'Porsche'), ('Ram', 'Ram'), ('Rolls-Royce', 'Rolls-Royce'), ('Saab', 'Saab'), ('Scion', 'Scion'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Saturn', 'Saturn'), ('Kia', 'Kia'), ('Geely', 'Geely'), ('MG', 'MG')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Activity_Id',
            field=models.CharField(default=masterlist.models.increment_Activity_Id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='BRAND',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Mitsubishi', 'Mitsubishi'), ('Ford', 'Ford'), ('Masda', 'Masda'), ('Isuzu', 'Isuzu'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('SuZuki', 'Suzuki'), ('Chevrolet', 'Chevrolet'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Bently', 'Bently'), ('Cadillac', 'Cadillac'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('GMC', 'GMC'), ('Genesis', 'Genesis'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mini', 'Mini'), ('Porsche', 'Porsche'), ('Ram', 'Ram'), ('Rolls-Royce', 'Rolls-Royce'), ('Saab', 'Saab'), ('Scion', 'Scion'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Saturn', 'Saturn'), ('Kia', 'Kia'), ('Geely', 'Geely'), ('MG', 'MG')], max_length=100, null=True),
        ),
    ]
