# Generated by Django 2.1.7 on 2020-03-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='BRAND',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Mitsubishi', 'Mitsubishi'), ('Ford', 'Ford'), ('Masda', 'Masda'), ('Isuzu', 'Isuzu'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('SuZuki', 'Suzuki'), ('Chevrolet', 'Chevrolet'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Bently', 'Bently'), ('Cadillac', 'Cadillac'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('GMC', 'GMC'), ('Genesis', 'Genesis'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mini', 'Mini'), ('Porsche', 'Porsche'), ('Ram', 'Ram'), ('Rolls-Royce', 'Rolls-Royce'), ('Saab', 'Saab'), ('Scion', 'Scion'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Saturn', 'Saturn')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='BRAND',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Mitsubishi', 'Mitsubishi'), ('Ford', 'Ford'), ('Masda', 'Masda'), ('Isuzu', 'Isuzu'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('SuZuki', 'Suzuki'), ('Chevrolet', 'Chevrolet'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Bently', 'Bently'), ('Cadillac', 'Cadillac'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('GMC', 'GMC'), ('Genesis', 'Genesis'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mini', 'Mini'), ('Porsche', 'Porsche'), ('Ram', 'Ram'), ('Rolls-Royce', 'Rolls-Royce'), ('Saab', 'Saab'), ('Scion', 'Scion'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Saturn', 'Saturn')], max_length=100, null=True),
        ),
    ]
