# Generated by Django 2.1.7 on 2020-06-02 02:32

from django.db import migrations, models
import masterlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0002_auto_20200601_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvehiclemasterlist',
            old_name='Smoke_Emission',
            new_name='Smoke_Emission_date',
        ),
        migrations.RenameField(
            model_name='vehiclemasterlist',
            old_name='Smoke_Emission',
            new_name='Smoke_Emission_date',
        ),
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='Activity_Id',
            field=models.CharField(default=masterlist.models.increment_Activity_Id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Activity_Id',
            field=models.CharField(default=masterlist.models.increment_Activity_Id, max_length=100, null=True),
        ),
    ]
