# Generated by Django 2.1.7 on 2021-03-15 11:06

from django.db import migrations, models
import masterlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0003_auto_20210312_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvehiclemasterlist',
            old_name='vehilcle_status',
            new_name='vehicle_status',
        ),
        migrations.RenameField(
            model_name='vehiclemasterlist',
            old_name='vehilcle_status',
            new_name='vehicle_status',
        ),
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='Activity_Id',
            field=models.CharField(default=masterlist.models.increment_Activity_Id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Activity_Id',
            field=models.CharField(default=masterlist.models.increment_Activity_Id, max_length=100, null=True),
        ),
    ]
