# Generated by Django 2.1.7 on 2021-05-22 7:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210415_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistration',
            name='email',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistration',
            name='Date_email_log',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Date_email_log',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
