# Generated by Django 3.2.3 on 2021-07-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petron_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordNumber', models.CharField(blank=True, max_length=254, null=True)),
                ('StatementNo', models.CharField(blank=True, max_length=254, null=True)),
                ('Account_Number', models.CharField(blank=True, max_length=254, null=True)),
                ('StatementDate', models.DateField(blank=True, null=True)),
                ('PaymentDueDate', models.DateField(blank=True, null=True)),
                ('PeriodCovered', models.DateField(blank=True, null=True)),
                ('CardNumber', models.CharField(blank=True, max_length=254, null=True)),
                ('ChargingDepartment', models.CharField(blank=True, max_length=254, null=True)),
                ('EmbossedName', models.CharField(blank=True, max_length=254, null=True)),
                ('PlateNumber', models.CharField(blank=True, max_length=254, null=True)),
                ('VehicleDescription', models.CharField(blank=True, max_length=254, null=True)),
                ('InvoiceDate', models.DateField(blank=True, null=True)),
                ('StationName', models.CharField(blank=True, max_length=254, null=True)),
                ('StationAddress', models.CharField(blank=True, max_length=254, null=True)),
                ('InvoiceNumber', models.CharField(blank=True, max_length=254, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=254, null=True)),
                ('ProductQuantity', models.CharField(blank=True, max_length=254, null=True)),
                ('ProductAmount', models.CharField(blank=True, max_length=254, null=True)),
                ('DiscountPerLitre', models.CharField(blank=True, max_length=254, null=True)),
                ('DiscountAmount', models.CharField(blank=True, max_length=254, null=True)),
                ('NetAmount', models.CharField(blank=True, max_length=254, null=True)),
                ('Odometer', models.CharField(blank=True, max_length=254, null=True)),
                ('KMDriven', models.CharField(blank=True, max_length=254, null=True)),
                ('Php_Km', models.CharField(blank=True, max_length=254, null=True)),
                ('Km_Li', models.CharField(blank=True, max_length=254, null=True)),
                ('FuelLimit', models.CharField(blank=True, max_length=254, null=True)),
                ('FuelLimitUnit', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
