# Generated by Django 3.2.3 on 2021-07-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petron_report',
            name='Supplier',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
