# Generated by Django 3.2.3 on 2021-07-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0003_auto_20210707_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petron_report',
            name='PeriodCovered',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
