# Generated by Django 3.2.3 on 2021-07-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0004_alter_petron_report_periodcovered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petron_report',
            name='InvoiceDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
