# Generated by Django 3.2.3 on 2021-07-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0005_alter_petron_report_invoicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petron_report',
            name='DiscountAmount',
            field=models.FloatField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='petron_report',
            name='DiscountPerLitre',
            field=models.FloatField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='petron_report',
            name='NetAmount',
            field=models.FloatField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='petron_report',
            name='ProductAmount',
            field=models.FloatField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='petron_report',
            name='ProductQuantity',
            field=models.FloatField(blank=True, max_length=254, null=True),
        ),
    ]
