# Generated by Django 3.2.3 on 2021-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0007_petron_pivot'),
    ]

    operations = [
        migrations.AddField(
            model_name='petron_report',
            name='Lubes_limit_unit',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='petron_report',
            name='Others_limits',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='petron_report',
            name='Services_limit',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='petron_report',
            name='Treats_limit',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
