# Generated by Django 3.2.3 on 2021-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_masterlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='EMAIL',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='EMAIL',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
