# Generated by Django 3.2.3 on 2021-08-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_masterlist', '0002_auto_20210823_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='Date_email_log',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='sent_email',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='Date_email_log',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='sent_email',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
