# Generated by Django 3.2.3 on 2021-09-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_masterlist', '0003_auto_20210831_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvehiclemasterlist',
            name='sent_email',
        ),
        migrations.RemoveField(
            model_name='vehiclemasterlist',
            name='sent_email',
        ),
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='Status_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='Status_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='Status_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='Status_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='Status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
