# Generated by Django 3.2.3 on 2021-11-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_masterlist', '0004_auto_20210903_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiclemasterlist',
            name='Status_4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemasterlist',
            name='Status_4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
