# Generated by Django 3.2.3 on 2022-02-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_masterlist', '0006_auto_20220104_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='COC_Date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='Last_Registration_Date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='ORIGINAL_OR_DATE',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='PLATE_NUMBER_RELEASE_DATE',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemasterlist',
            name='Smoke_Emission_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='COC_Date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Last_Registration_Date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='ORIGINAL_OR_DATE',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='PLATE_NUMBER_RELEASE_DATE',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterlist',
            name='Smoke_Emission_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
