# Generated by Django 3.2.3 on 2021-09-28 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('sent_email', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_Id', models.CharField(default=registration.models.increment_Activity_Id, max_length=100, null=True)),
                ('NO', models.CharField(default=registration.models.increment_NO, max_length=100, null=True)),
                ('PLATE_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('Plate_ending', models.CharField(blank=True, max_length=10, null=True)),
                ('CS_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('CR_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('MODEL', models.CharField(blank=True, max_length=10, null=True)),
                ('BRAND', models.CharField(choices=[('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Mitsubishi', 'Mitsubishi'), ('Ford', 'Ford'), ('Masda', 'Masda'), ('Isuzu', 'Isuzu'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('SuZuki', 'Suzuki'), ('Chevrolet', 'Chevrolet'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Bently', 'Bently'), ('Cadillac', 'Cadillac'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('GMC', 'GMC'), ('Genesis', 'Genesis'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mini', 'Mini'), ('Porsche', 'Porsche'), ('Ram', 'Ram'), ('Rolls-Royce', 'Rolls-Royce'), ('Saab', 'Saab'), ('Scion', 'Scion'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Saturn', 'Saturn'), ('Kia', 'Kia'), ('Geely', 'Geely'), ('MG', 'MG')], max_length=100, null=True)),
                ('VEHICLE_MAKE', models.CharField(blank=True, max_length=100, null=True)),
                ('ENGINE_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('CHASSIS_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('MV_FILE_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('COC', models.CharField(blank=True, max_length=225, null=True)),
                ('SMOKE_TPL', models.CharField(blank=True, max_length=225, null=True)),
                ('REMARKS_REGISTERED', models.CharField(blank=True, max_length=225, null=True)),
                ('DATE_EMAILED', models.CharField(blank=True, max_length=225, null=True)),
                ('JUSTIFICATION_REMARKS', models.CharField(blank=True, max_length=225, null=True)),
                ('Registration_month', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_email', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('Date_email_log', models.CharField(blank=True, max_length=20, null=True)),
                ('Date_registered', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRegistration',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Activity_Id', models.CharField(default=registration.models.increment_Activity_Id, max_length=100, null=True)),
                ('NO', models.CharField(default=registration.models.increment_NO, max_length=100, null=True)),
                ('PLATE_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('Plate_ending', models.CharField(blank=True, max_length=10, null=True)),
                ('CS_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('CR_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('MODEL', models.CharField(blank=True, max_length=10, null=True)),
                ('BRAND', models.CharField(choices=[('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Mitsubishi', 'Mitsubishi'), ('Ford', 'Ford'), ('Masda', 'Masda'), ('Isuzu', 'Isuzu'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('SuZuki', 'Suzuki'), ('Chevrolet', 'Chevrolet'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Bently', 'Bently'), ('Cadillac', 'Cadillac'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('GMC', 'GMC'), ('Genesis', 'Genesis'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mini', 'Mini'), ('Porsche', 'Porsche'), ('Ram', 'Ram'), ('Rolls-Royce', 'Rolls-Royce'), ('Saab', 'Saab'), ('Scion', 'Scion'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Saturn', 'Saturn'), ('Kia', 'Kia'), ('Geely', 'Geely'), ('MG', 'MG')], max_length=100, null=True)),
                ('VEHICLE_MAKE', models.CharField(blank=True, max_length=100, null=True)),
                ('ENGINE_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('CHASSIS_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('MV_FILE_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('COC', models.CharField(blank=True, max_length=225, null=True)),
                ('SMOKE_TPL', models.CharField(blank=True, max_length=225, null=True)),
                ('REMARKS_REGISTERED', models.CharField(blank=True, max_length=225, null=True)),
                ('DATE_EMAILED', models.CharField(blank=True, max_length=225, null=True)),
                ('JUSTIFICATION_REMARKS', models.CharField(blank=True, max_length=225, null=True)),
                ('Registration_month', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_email', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('Date_email_log', models.CharField(blank=True, max_length=20, null=True)),
                ('Date_registered', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical registration',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
