# Generated by Django 3.2.3 on 2021-05-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregistration',
            name='Date_email_log',
        ),
        migrations.RemoveField(
            model_name='historicalregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Date_email_log',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
    ]
