# Generated by Django 2.1.7 on 2021-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210316_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistration',
            name='Registration_month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Registration_month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
