# Generated by Django 2.1.7 on 2021-04-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210316_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('sent_email', models.CharField(max_length=10)),
            ],
        ),
    ]
