# Generated by Django 2.1.7 on 2021-04-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_carregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistration',
            name='sent_email',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='sent_email',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
