# Generated by Django 2.1.7 on 2021-04-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210415_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistration',
            name='Plate_ending',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistration',
            name='Reg_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Plate_ending',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Reg_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
