# Generated by Django 2.1.7 on 2021-04-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210419_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregistration',
            name='Reg_month',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Reg_month',
        ),
    ]
