# Generated by Django 3.2.3 on 2021-10-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasingmasterlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleasing',
            name='ACQUISITION_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='ACQUISITION_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
