# Generated by Django 3.2.3 on 2021-09-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report_shell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shell_pivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChargingDepartment', models.CharField(blank=True, max_length=254, null=True)),
                ('sum_product_amount', models.CharField(blank=True, max_length=254, null=True)),
                ('sum_disc_amount', models.CharField(blank=True, max_length=254, null=True)),
                ('sum_net_amount', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
