# # Generated by Django 3.2.3 on 2021-05-22 20:06

# from django.db import migrations, models
# import request.models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('request', '0001_initial'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='carrentalrequest',
#             name='Activity_id',
#             field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
#         ),
#         migrations.AlterField(
#             model_name='gas_card',
#             name='Activity_id',
#             field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
#         ),
#         migrations.AlterField(
#             model_name='historicalcarrentalrequest',
#             name='Activity_id',
#             field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
#         ),
#         migrations.AlterField(
#             model_name='historicalgas_card',
#             name='Activity_id',
#             field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
#         ),
#         migrations.AlterField(
#             model_name='historicalservice_vehicle',
#             name='Activity_id',
#             field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
#         ),
#         migrations.AlterField(
#             model_name='service_vehicle',
#             name='Activity_id',
#             field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
#         ),
#     ]
