# Generated by Django 3.2.3 on 2021-05-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210419_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle_repair',
            name='Date_email_log',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle_repair',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_repair',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_repair',
            name='Date_email_log',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
