# Generated by Django 2.1.7 on 2020-06-13 06:48

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20200602_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gas_card',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcarrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgas_card',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalservice_vehicle',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalservice_vehicle',
            name='Deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service_vehicle',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_vehicle',
            name='Deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
