# Generated by Django 2.1.7 on 2021-03-17 09:55

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20200613_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle_repair',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_repair',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gas_card',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcarrentalrequest',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgas_card',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalservice_vehicle',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalservice_vehicle',
            name='Deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalservice_vehicle',
            name='prefered_vehicle',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV '), ('Pick up 4x2', 'Pick up 4x2'), ('Pick Up 4x4', 'Pick Up 4x4'), ('AUV', 'AUV'), ('Others', 'Others ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_vehicle',
            name='Activity_id',
            field=models.CharField(default=request.models.increment_Activity_id, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_vehicle',
            name='Deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service_vehicle',
            name='prefered_vehicle',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV '), ('Pick up 4x2', 'Pick up 4x2'), ('Pick Up 4x4', 'Pick Up 4x4'), ('AUV', 'AUV'), ('Others', 'Others ')], max_length=100, null=True),
        ),
    ]
