# Generated by Django 3.2.3 on 2021-09-29 07:25

import car_rental_request.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=car_rental_request.models.increment_Activity_id, max_length=100, null=True)),
                ('A_Employee', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_received', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Fname', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Lname', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Assignee_Company', models.CharField(blank=True, max_length=200, null=True)),
                ('Assignee_band', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Dept', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Cost', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Div', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Loc', models.CharField(blank=True, max_length=200, null=True)),
                ('Assignee_Section', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_ATD', models.CharField(blank=True, max_length=100, null=True)),
                ('Vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_to', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.CharField(blank=True, max_length=100, null=True)),
                ('Place_of_del', models.CharField(blank=True, max_length=100, null=True)),
                ('type_rental', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=50, null=True)),
                ('Cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('Rental_period', models.CharField(blank=True, max_length=100, null=True)),
                ('Destination', models.CharField(blank=True, max_length=100, null=True)),
                ('Delivery_date', models.CharField(blank=True, max_length=100, null=True)),
                ('End_user', models.CharField(blank=True, max_length=100, null=True)),
                ('Type_of_vehicle', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('VAN', 'VAN')], max_length=50, null=True)),
                ('Plate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('Immediate_supervisor', models.CharField(blank=True, choices=[('Ser Roy DelaCruz', 'Ser Roy DelaCruz'), ('Adolfo Carlos Umali', 'Adolfo Carlos Umali')], max_length=50, null=True)),
                ('CR_SLA', models.CharField(blank=True, max_length=10, null=True)),
                ('Date_initiated', models.DateField(auto_now=True)),
                ('Deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCarRentalRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Activity_id', models.CharField(default=car_rental_request.models.increment_Activity_id, max_length=100, null=True)),
                ('A_Employee', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_received', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Fname', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Lname', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Assignee_Company', models.CharField(blank=True, max_length=200, null=True)),
                ('Assignee_band', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Dept', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Cost', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Div', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Loc', models.CharField(blank=True, max_length=200, null=True)),
                ('Assignee_Section', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignee_ATD', models.CharField(blank=True, max_length=100, null=True)),
                ('Vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_to', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.CharField(blank=True, max_length=100, null=True)),
                ('Place_of_del', models.CharField(blank=True, max_length=100, null=True)),
                ('type_rental', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=50, null=True)),
                ('Cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('Rental_period', models.CharField(blank=True, max_length=100, null=True)),
                ('Destination', models.CharField(blank=True, max_length=100, null=True)),
                ('Delivery_date', models.CharField(blank=True, max_length=100, null=True)),
                ('End_user', models.CharField(blank=True, max_length=100, null=True)),
                ('Type_of_vehicle', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('VAN', 'VAN')], max_length=50, null=True)),
                ('Plate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('Immediate_supervisor', models.CharField(blank=True, choices=[('Ser Roy DelaCruz', 'Ser Roy DelaCruz'), ('Adolfo Carlos Umali', 'Adolfo Carlos Umali')], max_length=50, null=True)),
                ('CR_SLA', models.CharField(blank=True, max_length=10, null=True)),
                ('Date_initiated', models.DateField(blank=True, editable=False)),
                ('Deadline', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical car rental request',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
