# Generated by Django 2.1.7 on 2020-05-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('in_payment_of', models.CharField(blank=True, max_length=250, null=True)),
                ('soa_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('date_bill', models.DateField(blank=True, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
