# Generated by Django 3.2.3 on 2021-07-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='date_initiated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbilling',
            name='date_initiated',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalownership',
            name='status',
            field=models.CharField(blank=True, choices=[('ON GOING ROUTING FOR APPROVAL', 'ON GOING ROUTING FOR APPROVAL'), ('NOTARIZED', 'NOTARIZED'), ('FOR TMG APPEARANCE', 'FOR TMG APPEARANCE'), ('WITH_TMG SCHEDULE', 'WITH TMG SCHEDULE'), ('WITH_MACRO ETCHING', 'WITH MACRO ETCHING'), ('FLEET VISMIN', 'FLEET VISMIN'), ('LTO TRANSFER', 'LTO TRANSFER')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='status',
            field=models.CharField(blank=True, choices=[('ON GOING ROUTING FOR APPROVAL', 'ON GOING ROUTING FOR APPROVAL'), ('NOTARIZED', 'NOTARIZED'), ('FOR TMG APPEARANCE', 'FOR TMG APPEARANCE'), ('WITH_TMG SCHEDULE', 'WITH TMG SCHEDULE'), ('WITH_MACRO ETCHING', 'WITH MACRO ETCHING'), ('FLEET VISMIN', 'FLEET VISMIN'), ('LTO TRANSFER', 'LTO TRANSFER')], max_length=100, null=True),
        ),
    ]
