# Generated by Django 3.2.3 on 2021-10-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0002_auto_20210705_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalownership',
            name='D_status',
            field=models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='D_status',
            field=models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalownership',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Deceased', 'Deceased'), ('Early Availment', 'Early Availment'), ('End of Car Plan', 'End of Car Plan'), ('FSSV Availment', 'FSSV Availment'), ('Promotion', 'Promotion'), ('Resigned', 'Resigned'), ('Shift from Non-Sales to Sales', 'Shift from Non-Sales to Sales'), ('Shift from Sales to Non-Sales', 'Shift from Sales to Non-Sales'), ('Winning Bidder', 'Winning Bidder'), ('2nd Hand', '2nd Hand')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalownership',
            name='status',
            field=models.CharField(blank=True, choices=[('ON GOING ROUTING FOR APPROVAL', 'ON GOING ROUTING FOR APPROVAL'), ('NOTARIZED', 'NOTARIZED'), ('FOR TMG APPEARANCE', 'FOR TMG APPEARANCE'), ('WITH_TMG SCHEDULE', 'WITH TMG SCHEDULE'), ('WITH_MACRO ETCHING', 'WITH MACRO ETCHING'), ('FLEET VISMIN', 'FLEET VISMIN'), ('LTO TRANSFER', 'LTO TRANSFER'), ('DONE TRANSFERRED', 'DONE TRANSFERRED'), ('FOR PULL OUT ORCR', 'FOR PULL OUT ORCR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Deceased', 'Deceased'), ('Early Availment', 'Early Availment'), ('End of Car Plan', 'End of Car Plan'), ('FSSV Availment', 'FSSV Availment'), ('Promotion', 'Promotion'), ('Resigned', 'Resigned'), ('Shift from Non-Sales to Sales', 'Shift from Non-Sales to Sales'), ('Shift from Sales to Non-Sales', 'Shift from Sales to Non-Sales'), ('Winning Bidder', 'Winning Bidder'), ('2nd Hand', '2nd Hand')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='status',
            field=models.CharField(blank=True, choices=[('ON GOING ROUTING FOR APPROVAL', 'ON GOING ROUTING FOR APPROVAL'), ('NOTARIZED', 'NOTARIZED'), ('FOR TMG APPEARANCE', 'FOR TMG APPEARANCE'), ('WITH_TMG SCHEDULE', 'WITH TMG SCHEDULE'), ('WITH_MACRO ETCHING', 'WITH MACRO ETCHING'), ('FLEET VISMIN', 'FLEET VISMIN'), ('LTO TRANSFER', 'LTO TRANSFER'), ('DONE TRANSFERRED', 'DONE TRANSFERRED'), ('FOR PULL OUT ORCR', 'FOR PULL OUT ORCR')], max_length=100, null=True),
        ),
    ]
