# Generated by Django 3.2.3 on 2022-02-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0003_auto_20211007_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalownership',
            old_name='deed_signed',
            new_name='recieved_for_pullout',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='deed_signed',
            new_name='recieved_for_pullout',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='date_initiated',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='doc_date_completed',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='forwarded_fleet_liason',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='forwarded_to_liason',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='req_Fname',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='req_Lname',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='req_band',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='req_cost',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='req_employee_id',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='req_title',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='return_fleet_admin',
        ),
        migrations.RemoveField(
            model_name='historicalownership',
            name='tmg_location',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='date_initiated',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='doc_date_completed',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='forwarded_fleet_liason',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='forwarded_to_liason',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='req_Fname',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='req_Lname',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='req_band',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='req_cost',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='req_employee_id',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='req_title',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='return_fleet_admin',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='tmg_location',
        ),
        migrations.AddField(
            model_name='historicalownership',
            name='Remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='Remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
