# Generated by Django 3.2.3 on 2022-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0004_auto_20220223_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalownership',
            name='date_application',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='date_application',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
