# Generated by Django 3.2.3 on 2022-03-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0006_auto_20220305_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalownership',
            name='date_application',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='date_application',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
