# Generated by Django 3.2.3 on 2021-10-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20210928_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='fata_monitoring',
            name='Status',
            field=models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalfata_monitoring',
            name='Status',
            field=models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=255, null=True),
        ),
    ]
