from django.db import models
import datetime
from django.utils import timezone
import datetime
from django.db.models import DateTimeField,DateField
from datetime import date,timedelta
from django.urls import reverse




class shell_report(models.Model):
	AccountNumber = models.CharField(max_length=254, null=True, blank=True)
	CustomerName1 = models.CharField(max_length=254, null=True, blank=True)
	FullCardNumber = models.CharField(max_length=254, null=True, blank=True)
	DelcoListPrice = models.CharField(max_length=254, null=True, blank=True)
	NetCustomerAmount = models.FloatField(max_length=254, null=True, blank=True)
	CardSequenceNumber = models.CharField(max_length=254, null=True, blank=True)
	CheckDigit = models.CharField(max_length=254, null=True, blank=True)
	DelcoGrossValue = models.FloatField(max_length=254, null=True, blank=True)
	DelcoVatAmount = models.FloatField(max_length=254, null=True, blank=True)
	DelcoVatRate = models.FloatField(max_length=254, null=True, blank=True)
	RebateCustAmount = models.FloatField(max_length=254, null=True, blank=True)
	VATNetAmount = models.FloatField(max_length=254, null=True, blank=True)
	DelcoRebateRate = models.FloatField(max_length=254, null=True, blank=True)
	VoucherNumber = models.CharField(max_length=254, null=True, blank=True)
	FleetId = models.CharField(max_length=254, null=True, blank=True)
	Quantity = models.FloatField(max_length=254, null=True, blank=True)
	DialogueIndicator = models.CharField(max_length=254, null=True, blank=True)
	IssuerCode1 = models.CharField(max_length=254, null=True, blank=True)
	NetInvoiceIndicator = models.CharField(max_length=254, null=True, blank=True)
	NetworkCode = models.CharField(max_length=254, null=True, blank=True)
	CardGroupName = models.CharField(max_length=254, null=True, blank=True)
	CardHolderName = models.CharField(max_length=254, null=True, blank=True)
	CardVehicleRegistrationNumber = models.CharField(max_length=254, null=True, blank=True)
	DeliveryNetAmount = models.FloatField(max_length=254, null=True, blank=True)
	PinIndicator = models.CharField(max_length=254, null=True, blank=True)
	RebateType = models.CharField(max_length=254, null=True, blank=True)
	RecordType = models.CharField(max_length=254, null=True, blank=True)
	ReleaseCode = models.CharField(max_length=254, null=True, blank=True)
	Time = models.TimeField(auto_now=False, auto_now_add=False,null=True, blank=True)
	TransactionStatus = models.CharField(max_length=254, null=True, blank=True)
	TransactionType1 = models.CharField(max_length=254, null=True, blank=True)
	VATIndicator = models.CharField(max_length=254, null=True, blank=True)
	VatUsage = models.FloatField(max_length=254, null=True, blank=True)
	IssuerCountry = models.CharField(max_length=254, null=True, blank=True)
	DelcoCode = models.CharField(max_length=254, null=True, blank=True)
	DelcoCountryCode1 = models.CharField(max_length=254, null=True, blank=True)
	TransactionCurrency = models.CharField(max_length=254, null=True, blank=True)
	InvoiceNumber = models.CharField(max_length=254, null=True, blank=True)
	InvoiceDate = models.DateField(auto_now=False,auto_now_add=False, null=True, blank=True)
	ProductCode = models.CharField(max_length=254, null=True, blank=True)
	SiteCode = models.CharField(max_length=254, null=True, blank=True)
	Site = models.CharField(max_length=254, null=True, blank=True)
	DeliveryDate = models.CharField(max_length=254, null=True, blank=True)
	OdometerReading1 = models.CharField(max_length=254, null=True, blank=True)
	DelcoCustRate1 = models.CharField(max_length=254, null=True, blank=True)
	CustomerCurrencyName1 = models.CharField(max_length=254, null=True, blank=True)
	DelcoPumpPrice = models.FloatField(max_length=254, null=True, blank=True)
	DelcoRebateAmount1 = models.FloatField(max_length=254, null=True, blank=True)
	CustRebateRate1 = models.FloatField(max_length=254, null=True, blank=True)
	PayerDisplayName = models.CharField(max_length=254, null=True, blank=True)
	PayerCode = models.CharField(max_length=254, null=True, blank=True)
	CardGroupID = models.CharField(max_length=254, null=True, blank=True)
	ProductName = models.CharField(max_length=254, null=True, blank=True)
	CreditDebitCode = models.CharField(max_length=254, null=True, blank=True)
	CorrectionFlag = models.CharField(max_length=254, null=True, blank=True)
	DelcoCountryCode = models.CharField(max_length=254, null=True, blank=True)
	VATApplicable = models.CharField(max_length=254, null=True, blank=True)
	CustomerEuroRate = models.FloatField(max_length=254, null=True, blank=True)
	DelcoEuroRate = models.FloatField(max_length=254, null=True, blank=True)
	EuroRebateAmount = models.FloatField(max_length=254, null=True, blank=True)
	EuroVATAmount = models.FloatField(max_length=254, null=True, blank=True)
	InvoiceSequenceNo = models.CharField(max_length=254, null=True, blank=True)
	ListPriceInTransactionCurrency = models.CharField(max_length=254, null=True, blank=True)
	NetEuroAmount = models.FloatField(max_length=254, null=True, blank=True)
	PumpPriceInTransactionCurrency = models.FloatField(max_length=254, null=True, blank=True)
	RebateonNetAmountInCustomerCurrency = models.FloatField(max_length=254, null=True, blank=True)
	RebateonNetAmountInTransactionCurrency = models.FloatField(max_length=254, null=True, blank=True)
	RebateRate = models.FloatField(max_length=254, null=True, blank=True)
	UnInvoiceSequenceNo = models.CharField(max_length=254, null=True, blank=True)
	NetworkName = models.CharField(max_length=254, null=True, blank=True)
	Additional1 = models.CharField(max_length=254, null=True, blank=True)
	Additional2 = models.CharField(max_length=254, null=True, blank=True)
	Additional3 = models.CharField(max_length=254, null=True, blank=True)
	Additional4 = models.CharField(max_length=254, null=True, blank=True)
	TransactionIdentifier = models.CharField(max_length=254, null=True, blank=True)
	TransactionAuthorisationCode = models.CharField(max_length=254, null=True, blank=True)
	DelcoName = models.CharField(max_length=254, null=True, blank=True)
	SiteGroupid = models.CharField(max_length=254, null=True, blank=True)
	SiteGroupName = models.CharField(max_length=254, null=True, blank=True)
	Cardtype = models.CharField(max_length=254, null=True, blank=True)
	PayerGroup = models.CharField(max_length=254, null=True, blank=True)
	PayerNumber = models.CharField(max_length=254, null=True, blank=True)
	RefundFlag = models.CharField(max_length=254, null=True, blank=True)
	RefundOriginalTransactionId = models.CharField(max_length=254, null=True, blank=True)
	PostingDate = models.CharField(max_length=254, null=True, blank=True)
	PostingTime = models.TimeField(auto_now=False,auto_now_add=False, null=True, blank=True)
	CustomerReferenceValue = models.CharField(max_length=254, null=True, blank=True)
	CustomerReferenceDescription = models.CharField(max_length=254, null=True, blank=True)
	CardPayerAssociationCode = models.CharField(max_length=254, null=True, blank=True)
	CardPayerAssociation = models.CharField(max_length=254, null=True, blank=True)
	IncomingProductCode = models.CharField(max_length=254, null=True, blank=True)
	TransactionProviderId = models.CharField(max_length=254, null=True, blank=True)
	TransactionProviderName = models.CharField(max_length=254, null=True, blank=True)
	FileName = models.CharField(max_length=254, null=True, blank=True)
	FileDate = models.CharField(max_length=254, null=True, blank=True)
	AccountGroup3Code = models.CharField(max_length=254, null=True, blank=True)
	AccountGroup3Name = models.CharField(max_length=254, null=True, blank=True)
	ContractedRebateRate = models.FloatField(max_length=254, null=True, blank=True)
	IsBestOfPricingApplicable = models.CharField(max_length=254, null=True, blank=True)
	CostCenter = models.CharField(max_length=254, null=True, blank=True)
	Supplier = models.CharField(max_length=254, null=True, blank=True)
	# def save(self, *args, **kwargs):
	# 	self.NetCustomerAmount= round(self.NetCustomerAmount, 2)
	# 	self.DelcoGrossValue= round(self.DelcoGrossValue, 2)
	# 	self.DelcoVatAmount= round(self.DelcoVatAmount, 2)
	# 	self.DelcoVatRate= round(self.DelcoVatRate, 2)
	# 	self.RebateCustAmount= round(self.RebateCustAmount, 2)
	# 	self.VATNetAmount= round(self.VATNetAmount, 2)
	# 	self.DelcoRebateRate= round(self.DelcoRebateRate, 2)
	# 	self.Quantity= round(self.Quantity, 2)
	# 	self.DelcoPumpPrice= round(self.DelcoPumpPrice, 2)
	# 	self.DelcoRebateAmount1= round(self.DelcoRebateAmount1, 2)
	# 	self.CustRebateRate1= round(self.CustRebateRate1, 2)
	# 	self.CustomerEuroRate= round(self.CustomerEuroRate, 2)
	# 	self.DelcoEuroRate= round(self.DelcoEuroRate, 2)
	# 	self.EuroRebateAmount= round(self.EuroRebateAmount, 2)
	# 	self.EuroVATAmount= round(self.EuroVATAmount, 2)
	# 	self.NetEuroAmount= round(self.NetEuroAmount, 2)
	# 	self.PumpPriceInTransactionCurrency= round(self.PumpPriceInTransactionCurrency, 2)
	# 	self.RebateonNetAmountInCustomerCurrency= round(self.RebateonNetAmountInCustomerCurrency, 2)
	# 	self.RebateonNetAmountInTransactionCurrency= round(self.RebateonNetAmountInTransactionCurrency, 2)
	# 	self.RebateRate= round(self.RebateRate, 2)
	# 	self.ContractedRebateRate= round(self.ContractedRebateRate, 2)
	# 	super(shell_report, self).save(*args, **kwargs)

	def __str__(self):
		return self.AccountNumber

	def get_absolute_url(self):
		return reverse('report_shell_list')

class shell_pivot(models.Model):
	ChargingDepartment = models.CharField(max_length=254, null=True, blank=True)
	sum_delco_gross = models.CharField(max_length=254, null=True, blank=True)
	Sum_total_net = models.CharField(max_length=254, null=True, blank=True)
