# Generated by Django 3.2.3 on 2021-09-29 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service_request.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='service_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(default=service_request.models.increment_Activity_id, max_length=100, null=True)),
                ('request_date', models.CharField(blank=True, max_length=100, null=True)),
                ('req_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('req_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('req_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_group', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_costcenter', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_section', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_location', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_atd', models.CharField(blank=True, max_length=100, null=True)),
                ('new_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('new_employee_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('new_employee_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('new_employee_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('new_temporary_atd', models.CharField(blank=True, max_length=100, null=True)),
                ('prefered_vehicle', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV '), ('Pick up 4x2', 'Pick up 4x2'), ('Pick Up 4x4', 'Pick Up 4x4'), ('AUV', 'AUV'), ('Others', 'Others ')], max_length=100, null=True)),
                ('justification', models.CharField(blank=True, max_length=100, null=True)),
                ('E_plate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('E_con_sticker', models.CharField(blank=True, max_length=100, null=True)),
                ('E_model_year', models.CharField(blank=True, max_length=100, null=True)),
                ('E_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('E_make', models.CharField(blank=True, max_length=100, null=True)),
                ('E_type', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, choices=[('Ser Roy Dela Cruz', 'Ser Roy Dela Cruz'), ('Adolfo Carlos Umali', 'Adolfo Carlos Umali ')], max_length=100, null=True)),
                ('approved_date', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_provider', models.CharField(blank=True, choices=[('Orix', 'Orix'), ('Diamond', 'Diamond '), ('Safari', 'Safari')], max_length=100, null=True)),
                ('vehicle_plate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_CS_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_brand', models.CharField(blank=True, choices=[('BMW', 'BMW'), ('Chevrolet', 'Chevrolet '), ('chrysler', 'chrysler'), ('Ford', 'Ford'), ('Honda', 'Honda '), ('Hyundai', 'Hyundai'), ('Isuzu', 'Isuzu'), ('Kia', 'Kia '), ('Masda', 'Masda'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan '), ('Peugeot', 'Peugeot'), ('Subaro', 'Subaro')], max_length=100, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('SVV_SLA', models.CharField(blank=True, max_length=10, null=True)),
                ('date_initiated', models.DateField(auto_now=True, null=True)),
                ('Deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historicalservice_vehicle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Activity_id', models.CharField(default=service_request.models.increment_Activity_id, max_length=100, null=True)),
                ('request_date', models.CharField(blank=True, max_length=100, null=True)),
                ('req_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('req_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('req_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_group', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_costcenter', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_section', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_location', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_atd', models.CharField(blank=True, max_length=100, null=True)),
                ('new_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('new_employee_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('new_employee_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('new_employee_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('new_temporary_atd', models.CharField(blank=True, max_length=100, null=True)),
                ('prefered_vehicle', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV '), ('Pick up 4x2', 'Pick up 4x2'), ('Pick Up 4x4', 'Pick Up 4x4'), ('AUV', 'AUV'), ('Others', 'Others ')], max_length=100, null=True)),
                ('justification', models.CharField(blank=True, max_length=100, null=True)),
                ('E_plate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('E_con_sticker', models.CharField(blank=True, max_length=100, null=True)),
                ('E_model_year', models.CharField(blank=True, max_length=100, null=True)),
                ('E_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('E_make', models.CharField(blank=True, max_length=100, null=True)),
                ('E_type', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, choices=[('Ser Roy Dela Cruz', 'Ser Roy Dela Cruz'), ('Adolfo Carlos Umali', 'Adolfo Carlos Umali ')], max_length=100, null=True)),
                ('approved_date', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_provider', models.CharField(blank=True, choices=[('Orix', 'Orix'), ('Diamond', 'Diamond '), ('Safari', 'Safari')], max_length=100, null=True)),
                ('vehicle_plate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_CS_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_brand', models.CharField(blank=True, choices=[('BMW', 'BMW'), ('Chevrolet', 'Chevrolet '), ('chrysler', 'chrysler'), ('Ford', 'Ford'), ('Honda', 'Honda '), ('Hyundai', 'Hyundai'), ('Isuzu', 'Isuzu'), ('Kia', 'Kia '), ('Masda', 'Masda'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan '), ('Peugeot', 'Peugeot'), ('Subaro', 'Subaro')], max_length=100, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('SVV_SLA', models.CharField(blank=True, max_length=10, null=True)),
                ('date_initiated', models.DateField(blank=True, editable=False, null=True)),
                ('Deadline', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical service_vehicle',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
